import type { NextPage } from "next";
import Head from "next/head";

import { Hero, Testimonial,  LatestArticles, Accesories, ContactUs, CallToAction } from "../components";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Mimini</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mimini-icon.ico" />
      </Head>

      <main className='flex flex-col space-y-8'>
        <Hero />
        <Testimonial/>
        <LatestArticles/>
        <Accesories/>
        <ContactUs/>
        <CallToAction/>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
